// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIFoodPet.Models;

namespace WebAPIFoodPet.Migrations
{
   //[DbContext(typeof(MyDbContext))]
    partial class WebAPIFoodPetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPIFoodPet.Models.Cardapio", b =>
                {
                    b.Property<int>("IDPrato")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DsPrato");

                    b.Property<int?>("PedidoID");

                    b.Property<double>("Valor");

                    b.HasKey("IDPrato");

                    b.HasIndex("PedidoID");

                    b.ToTable("Cardapio");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.ClienteDados", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<int>("ClienteTelefone");

                    b.Property<string>("NomeCliente");

                    b.Property<int?>("UsuariosUsuarioID");

                    b.HasKey("IDCliente");

                    b.HasIndex("UsuariosUsuarioID");

                    b.ToTable("ClienteDados");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.DadosPet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteDados_IDIDCliente");

                    b.Property<int>("IdadePet");

                    b.Property<string>("NomePet");

                    b.Property<int>("PesoPet");

                    b.HasKey("ID");

                    b.HasIndex("ClienteDados_IDIDCliente");

                    b.ToTable("DadosPets");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<int?>("ClienteDadosIDCliente");

                    b.Property<string>("Logradouro");

                    b.Property<string>("NmCep");

                    b.Property<int>("Numero");

                    b.HasKey("EnderecoID");

                    b.HasIndex("ClienteDadosIDCliente");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteDados_IDIDCliente");

                    b.Property<DateTime>("DtEntregaPedido");

                    b.Property<DateTime>("DtPedidoRealizado");

                    b.Property<double>("Total");

                    b.HasKey("PedidoID");

                    b.HasIndex("ClienteDados_IDIDCliente");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DtCriacao");

                    b.Property<string>("Email");

                    b.Property<string>("Senha");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.Cardapio", b =>
                {
                    b.HasOne("WebAPIFoodPet.Models.Pedido")
                        .WithMany("Pratos_ID")
                        .HasForeignKey("PedidoID");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.ClienteDados", b =>
                {
                    b.HasOne("WebAPIFoodPet.Models.Usuario", "Usuarios")
                        .WithMany("DadosUsuarios")
                        .HasForeignKey("UsuariosUsuarioID");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.DadosPet", b =>
                {
                    b.HasOne("WebAPIFoodPet.Models.ClienteDados", "ClienteDados_ID")
                        .WithMany("DadosPet_ID")
                        .HasForeignKey("ClienteDados_IDIDCliente");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.Endereco", b =>
                {
                    b.HasOne("WebAPIFoodPet.Models.ClienteDados", "ClienteDados")
                        .WithMany("Endereco_ID")
                        .HasForeignKey("ClienteDadosIDCliente");
                });

            modelBuilder.Entity("WebAPIFoodPet.Models.Pedido", b =>
                {
                    b.HasOne("WebAPIFoodPet.Models.ClienteDados", "ClienteDados_ID")
                        .WithMany("Pedido_ID")
                        .HasForeignKey("ClienteDados_IDIDCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
